//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using TallerMecanico.MVVM;

    public partial class averia:MVBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public averia()
        {
            this.pieza = new HashSet<pieza>();
        }
    
        public int CodigoAveria { get; set; }
        [Required]
        public string Descripcion { get; set; }
       [Range(0.0,Double.MaxValue,ErrorMessage ="No estan permitidos los valores negativos")]
        public Nullable<double> Precio { get; set; }
        public string Tipo { get; set; }
        [Required]
        public string Estado { get; set; }
        public Nullable<int> EmpleadoAsignado { get; set; }
        public string Resolucion { get; set; }
        [Required]
        public System.DateTime FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public int Cliente { get; set; }
        [MaxLength(340)]
        public string Observaciones { get; set; }
        [Required]
        public virtual cliente cliente1 { get; set; }
        public virtual empleado empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pieza> pieza { get; set; }
    }
}
