var namespace_taller_mecanico_1_1_vista_1_1_dialogos_1_1empleado_dialogo =
[
    [ "AddEmpleado", "class_taller_mecanico_1_1_vista_1_1_dialogos_1_1empleado_dialogo_1_1_add_empleado.html", "class_taller_mecanico_1_1_vista_1_1_dialogos_1_1empleado_dialogo_1_1_add_empleado" ],
    [ "BorrarEmpleado", "class_taller_mecanico_1_1_vista_1_1_dialogos_1_1empleado_dialogo_1_1_borrar_empleado.html", "class_taller_mecanico_1_1_vista_1_1_dialogos_1_1empleado_dialogo_1_1_borrar_empleado" ],
    [ "ModificarEmpleado", "class_taller_mecanico_1_1_vista_1_1_dialogos_1_1empleado_dialogo_1_1_modificar_empleado.html", "class_taller_mecanico_1_1_vista_1_1_dialogos_1_1empleado_dialogo_1_1_modificar_empleado" ]
];